spring:
  application:
    name: tenga
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://138.199.208.122:5433/postgres
    username: postgres
    password: PDOQUpYK45oZ3mUWp0GlQosGQGcdNCQOo0etkXgutvHUgx4LU6iZU9m3xQECRfy5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
